### ISSUE TITLE
Thank you! (+ example size)

### ISSUE THREAD

**Issue by BartMassey** [qtfkwk/cocomo#1]
Mostly not an actual issue — just wanted to say thanks for this. It seems to work great. Really appreciate your taking the time to write it.

(You might want to use a larger example than the 100-line one: COCOMO is especially bad for small programs, as it doesn't properly take into account the cost and complexity savings of small code. Or not: it *does* highlight the weakness of COCOMO, which is good for people to know.)

**Comment by qtfkwk** [comment]
Thanks for the kind note. You're welcome.

Using a clone of tokei (5567 SLOC) now so should serve as a better example.
